# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZndRDmf54U8ATmmF5E3FgVaUvP5BpvS
"""

!pip install catboost

!pip install fastapi uvicorn nest-asyncio pyngrok pandas catboost

!pip install python-multipart

from google.colab import drive
drive.mount('/content/drive')
from fastapi import FastAPI, File, UploadFile
import pandas as pd
from catboost import CatBoostClassifier
import io

app = FastAPI()

# Muat model CatBoost yang sudah disimpan
model_path = '/content/drive/MyDrive/KULIAH/SKRIPSI/model/catboost_Model_terbaik.cbm'
saved_model = CatBoostClassifier()
saved_model.load_model(model_path)


@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    # Baca file CSV yang diunggah
    contents = await file.read()
    df = pd.read_csv(io.BytesIO(contents))

    # Pastikan kolom SK_ID_CURR ada di dataset
    if "SK_ID_CURR" not in df.columns:
        return {"error": "Kolom SK_ID_CURR tidak ditemukan dalam dataset."}

    sk_id_curr = df["SK_ID_CURR"]
    X_test_unlabeled = df.drop(columns=["SK_ID_CURR"], errors="ignore")

    # Prediksi probabilitas gagal bayar
    y_test_pred_proba = saved_model.predict_proba(X_test_unlabeled)[:, 1]

    # Buat DataFrame hasil prediksi
    output = pd.DataFrame({
        "SK_ID_CURR": sk_id_curr,
        "TARGET": y_test_pred_proba
    })

    # Simpan hasil sebagai CSV
    output_csv = output.to_csv(index=False)

    return {"message": "Prediksi berhasil!", "csv_data": output_csv}

!cp /content/drive/MyDrive/KULIAH/SKRIPSI/model/catboost_Model_terbaik.cbm .